const quotes = [
    'Hard work always pays off, whatever you do.” – Dustin Lynch',
    'A lot of hard work is hidden behind nice things.” – Ralph Lauren',
    'Hard work pays off. The harder you work, the more people will notice.” – Sydney Sweeney',
    'Preparation for tomorrow is hard work today.” – Bruce Lee',
    'The hard work definitely paid off and hard work always does.” – Gabby Douglas',
    'I’ve learned that anything in life worth having comes from patience and hard work.” – Greg Behrendt',
    'Chop your own wood and it will warm you twice.” – Henry Ford',
    'Confidence and Hard-work is the best medicine to kill the disease called failure. It will make you a successful person.” – Abdul Kalam',
    'Great things come from hard work and perseverance. No excuses.” – Kobe Bryant',
    'Work hard, be kind, and amazing things will happen.” – Conan O’Brien',
    'Hard work pays off if you’re patient enough to see it through.” – Michael Chandler',
    'I do not know anyone who has got to the top without hard work. That is the recipe. It will not always get you to the top, but should get you pretty near.” – Margaret Thatcher',
    'If you do the work you get rewarded. There are no shortcuts in life.” – Michael Jordan',
    'I strongly believe if you work hard, whatever you want, it will come to you.” – Beyoncé Knowles-Carter',
    'Everybody wants to be famous, but nobody wants to do the work. I live by that. You grind hard so you can play hard. At the end of the day, you put all the work in, and eventually it’ll pay off. It could be in a year, it could be in 30 years. Eventually, your hard work will pay off.” – Kevin Hart',
    'Pain is temporary. Quitting lasts forever.” – Lance Armstrong',
    'Start by doing what’s necessary; then do what’s possible; and suddenly you are doing the impossible.” – Francis of Assisi',
    'The greater the effort, the greater the glory.” – Pierre Corneille',
    'Nothing will work unless you do.” – Maya Angelou',
    'Hard work spotlights the character of people: some turn up their sleeves, some turn up their noses, and some don’t turn up at all.” – Sam Ewing',
    'If you focus on results, you will never change. If you focus on change, you will get results.” – Jack Dixon',
    'Nobody who ever gave his best regretted it.” – George Halas',
    'I am who I am today because of the choices I made yesterday.” – Eleanor Roosevelt',
    'There are no shortcuts to any place worth going.” – Beverly Sills',
    'Without labor, nothing prospers.” – Sophocles',
    'The difference between try and triumph is just a little umph!” – Marvin Phillip',
    'The fight is won or lost far away from witnesses — behind the lines, in the gym, and out there on the road, long before I dance under those lights.” – Muhammad Ali',
    'There will be obstacles. There will be doubters. There will be mistakes. But with hard work, there are no limits.” – Michael Phelps',
    'There are no secrets to success. It is the result of preparation, hard work, and learning from failure.” – Colin Powell',
    'Success usually comes to those who are too busy to be looking for it.” – Henry David Thoreau',
    'The only difference between success and failure is the ability to take action.” – Alexander Graham Bell',
    'The elevator to success is out of order. You’ll have to use the stairs… one step at a time.” – Joe Girard.',
    'The dictionary is the only place that success comes before work.” – Vince Lombardi',
    'Striving for success without hard work is like trying to harvest where you haven’t planted.” – David Bly',
    'If everyone is moving forward together, then success takes care of itself.” – Henry Ford.',
    'Success is nothing more than a few simple disciplines, practiced every day.” – Jim Rohn',
    'I have learned that success is to be measured not so much by the position that one has reached in life as by the obstacles which he has had to overcome while trying to succeed.” – Booker T. Washington',
    'Success seems to be connected with action. Successful people keep moving. They make mistakes, but they don’t quit.” – Conrad Hilton',
    'Success is the sum of small efforts, repeated day in and day out.” – Robert Collier',
    'Success means doing the best we can with what we have. Success is the doing, not the getting; in the trying, not the triumph. Success is a personal standard, reaching for the highest that is in us, becoming all that we can be.” – Zig Ziglar',
    'Success is not final; failure is not fatal. It is the courage to continue that counts.” – Winston S. Churchill',
    'All roads that lead to success have to pass through hard work boulevard at some point.” – Eric Thomas',
    'Keep your dreams alive. Understand to achieve anything requires faith and belief in yourself, vision, hard work, determination, and dedication. Remember all things are possible for those who believe.” – Gail Devers',
    'Work hard in silence, let success be your noise.” – Frank Ocean',
    'It’s not about money or connections – it’s the willingness to outwork and outlearn everyone.” – Mark Cuban',
    'One important key to success is self-confidence. An important key to self-confidence is preparation.” – Arthur Ashe',
    'You must tell yourself, “No matter how hard it is, or how hard it gets, I’m going to make it.” – Les Brown.',
    'Self-Belief and hard work will always earn you success.” – Virat Kohli',
    'Believe in yourself, work hard, work smart and passionately present your best self to the world.” – Hill Harper',
    'If you really want something, and really work hard, and take advantage of opportunities, and never give up, you will find a way.” -Jane Goodall',
    'In a gentle way, you can shake the world.” – Mahatma Gandhi',
    'You can’t get there by bus, only by hard work and risk and by not quite knowing what you’re doing. What you’ll discover will be wonderful. What you’ll discover will be yourself.” – Alan Alda',
    'Worrying gets you nowhere. If you turn up worrying about how you’re going to perform, you’ve already lost. Train hard, turn up, run your best and the rest will take care of itself.” – Usain Bolt',
    'I’m a great believer in luck, and I find the harder I work the more I have of it.” – Thomas Jefferson',
    'Luck is a dividend of sweat. The more you sweat, the luckier you get.” – Ray Kroc',
    'The only thing that overcomes hard luck is hard work.” – Harry Golden',
    'Luck is tenacity of purpose.” – Elbert Hubbard',
    'I didn’t get there by wishing for it or hoping for it, but by working for it. – Estée Lauder',
    'Luck is what happens when preparation meets opportunity.” – Seneca',
    'I’ve found that luck is quite predictable. If you want more luck, take more chances. Be more active. Show up more often.” – Brian Tracy',
    'We must believe in luck. For how else can we explain the success of those we don’t like?” – Jean Cocteau',
    'When it comes to luck, you make your own.” – Bruce Springsteen',
    'Luck is not chance, it’s toil; fortune’s expensive smile is earned.” – Emily Dickinson',
    'A pound of pluck is worth a ton of luck.” – James A. Garfield',
    'I say luck is when an opportunity comes along and you’re prepared for it.” – Denzel Washington',
    'The fruit of your own hard work is the sweetest.” – Deepika Padukone',
    'Do not whine…Do not complain. Work harder. Spend more time alone.” – Joan Didion',
    'Let us make our future now, and let us make our dreams tomorrow’s reality.” – Malala Yousafzai',
    'The three great essentials to achieve anything worthwhile are Hard work, stick-to-itiveness, and common sense.” – Thomas Edison',
    '“If you have built castles in the air, your work need not be lost; that is where they should be. Now put the foundations under them.” – Henry David Thoreau',
    'Doing the best at this moment puts you in the best place for the next moment.” – Oprah Winfrey',
    'To achieve your dreams, work is required. Suffering is optional.” Jack Canfield',
    'The only way to achieve the impossible is to believe it is possible.” – Charles Kingsleigh',
    'There is no magic to achievement. It’s really about hard work, choices, and persistence.” – Michelle Obama',
    'In any given moment we have two options. To step forward into growth or to step back into safety.” – Abraham Maslow',
    'Do what you have to do until you can do what you want to do.” – Oprah Winfrey',
    'Talent is cheaper than table salt. What separates the talented individual from the successful one is a lot of hard work.” – Stephen King',
    'Hard work beats talent when talent doesn’t work hard.” – Tim Notke',
    'Talent means nothing, while experience, acquired in humility and with hard work, means everything.” – Patrick Suskind',
    'If people knew how hard I had to work to gain my mastery, it would not seem so wonderful at all.” – Michelangelo',
    'Success isn’t always about greatness. It’s about consistency. Consistent hard work leads to success. Greatness will come.” – Dwayne “the Rock” Johnson',
    'Intelligence without ambition is a bird without wings.” – Salvador Dali',
    'Nothing in this world can take the place of persistence. Talent will not: nothing is more common than unsuccessful men with talent. Genius will not; unrewarded genius is almost a proverb. Education will not: the world is full of educated derelicts. Persistence and determination alone are omnipotent.” – Calvin Coolidge',
    'Talent without working hard is nothing.” – Cristiano Ronaldo',
    'Talent is nothing without dedication and discipline, and dedication and discipline is a talent in itself.” – Luke Campbell',
    'There may be people who have more talent than you, but there’s no excuse for anyone to work harder than you do.” – Derek Jeter',
    'What you lack in talent can be made up with desire, hustle and giving 110 percent all the time.” – Don Zimmer',
    'Talent is given by God but you should respect it by doing good work.” – Johnny Lever',
    'The big talent is persistence.” – Octavia E. Butler',
    'Nothing in the world is worth having or worth doing unless it means effort, pain, difficulty… I have never in my life envied a human being who led an easy life. I have envied a great many people who led difficult lives and led them well.” – Theodore Roosevelt',
    'Perseverance is the hard work you do after you get tired of doing the hard work you already did.” – Newt Gingrich',
    'Nothing in the world can take the place of persistence.” – Calvin Coolidge',
    'Perseverance is failing 19 times and succeeding the 20th.” – Julie Andrews',
    'Perseverance, the secret of all triumphs.” – Victor Hugo',
    'Dreams are not easy. Dreams are painful. They force work and commitment. They are challenging and motivating.” – Robert Kiyosaki',
    'It’s hard to beat a person who doesn’t give up.” – Babe Ruth',
    'Without a struggle there can be no progress.” – Frederick Douglass',
    'Dreams can come true, but there is a secret. They’re realized through the magic of persistence, determination, commitment, passion, practice, focus & hard work. They happen a step at a time, manifested over years, not weeks.” – Elbert Hubbard',
];

export default quotes;
